// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGsdhNwrOCHAVosoiVCI0QM7bgFxHzRuE',
    appId: '1:485137437849:web:eaf194b0b85e2434509408',
    messagingSenderId: '485137437849',
    projectId: 'opd-connect',
    authDomain: 'opd-connect.firebaseapp.com',
    storageBucket: 'opd-connect.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_loZku3p_qkS0PWmCv0tpIGoPzc-wjaU',
    appId: '1:485137437849:android:cd49d4461c991383509408',
    messagingSenderId: '485137437849',
    projectId: 'opd-connect',
    storageBucket: 'opd-connect.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkd5qWABbXY4fja6Fo8qXrkpFkygF7X1s',
    appId: '1:485137437849:ios:f5be08e3ad803366509408',
    messagingSenderId: '485137437849',
    projectId: 'opd-connect',
    storageBucket: 'opd-connect.firebasestorage.app',
    iosBundleId: 'com.example.opdConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkd5qWABbXY4fja6Fo8qXrkpFkygF7X1s',
    appId: '1:485137437849:ios:f5be08e3ad803366509408',
    messagingSenderId: '485137437849',
    projectId: 'opd-connect',
    storageBucket: 'opd-connect.firebasestorage.app',
    iosBundleId: 'com.example.opdConnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGsdhNwrOCHAVosoiVCI0QM7bgFxHzRuE',
    appId: '1:485137437849:web:b0d712e5d3c0ebb2509408',
    messagingSenderId: '485137437849',
    projectId: 'opd-connect',
    authDomain: 'opd-connect.firebaseapp.com',
    storageBucket: 'opd-connect.firebasestorage.app',
  );
}
